const kittydata = [
  {
    id: 1,
    cryptoName: "Crazy Kitty",
    cryptoType: "CryptoKitty",
    artist: "Alice The Wonder",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty1.jpeg",
  },
  {
    id: 2,
    cryptoName: "Wild Kitty",
    cryptoType: "CryptoKitty",
    artist: "Jack From The Box",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty2.jpeg",
  },
  {
    id: 3,
    cryptoName: "Lost Kitty",
    cryptoType: "CryptoKitty",
    artist: "Rose Da Artist",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty3.jpeg",
  },
  {
    id: 4,
    cryptoName: "Confused Kitty",
    cryptoType: "CryptoKitty",
    artist: "Gnarly Artist Dude",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty4.jpeg",
  },
  {
    id: 5,
    cryptoName: "Pensive Kitty",
    cryptoType: "CryptoKitty",
    artist: "The Intellect",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty5.jpeg",
  },
  {
    id: 6,
    cryptoName: "Eclectic Kitty",
    cryptoType: "CryptoKitty",
    artist: "Max The Creator",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty6.jpeg",
  },
  {
    id: 7,
    cryptoName: "Radical Kitty",
    cryptoType: "CryptoKitty",
    artist: "Counter Culture",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty7.jpeg",
  },
  {
    id: 8,
    cryptoName: "Nerdy Kitty",
    cryptoType: "CryptoKitty",
    artist: "The Super Nerd",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty8.jpeg",
  },
  {
    id: 9,
    cryptoName: "Fluffy Kitty",
    cryptoType: "CryptoKitty",
    artist: "Jimmy The Reaper",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty9.jpeg",
  },
  {
    id: 10,
    cryptoName: "Sleepy Kitty",
    cryptoType: "CryptoKitty",
    artist: "Live Fast Die Young",
    collection: "Cute Crypto Kitties",
    image: "/images/cryptokitty10.jpeg",
  },
];
export default kittydata;
